import React from "react";
import {
    AlbumFillIcon,
    AlbumIcon,
    AlignCenterIcon,
    AlignJustifyIcon,
    AlignLeftIcon,
    AlignRightIcon,
    ArrowDownCircleFillIcon,
    ArrowDownCircleIcon,
    ArrowDownIcon,
    ArrowLeftCircleFillIcon,
    ArrowLeftCircleIcon,
    ArrowLeftDownIcon,
    ArrowLeftIcon,
    ArrowLeftUpIcon,
    ArrowRightCircleFillIcon,
    ArrowRightCircleIcon,
    ArrowRightDownIcon,
    ArrowRightIcon,
    ArrowRightUpIcon,
    ArrowUpCircleFillIcon,
    ArrowUpCircleIcon,
    ArrowUpIcon,
    BellFillIcon,
    BellIcon,
    BinFillIcon,
    BinIcon,
    BookmarkFillIcon,
    BookmarkIcon,
    BoxFillIcon,
    BoxIcon,
    BriefcaseFillIcon,
    BriefcaseIcon,
    BuildingIcon,
    CalendarCrossFillIcon,
    CalendarCrossIcon,
    CalendarDotFillIcon,
    CalendarDotIcon,
    CalendarEventFillIcon,
    CalendarEventIcon,
    CalendarFillIcon,
    CalendarIcon,
    CalendarPencilFillIcon,
    CalendarPencilIcon,
    CalendarPlusFillIcon,
    CalendarPlusIcon,
    CalendarTickFillIcon,
    CalendarTickIcon,
    CameraFillIcon,
    CameraIcon,
    CarIcon,
    CaretDownIcon,
    CaretLeftIcon,
    CaretRightIcon,
    CaretUpIcon,
    ChartFillIcon,
    ChartIcon,
    CheerFillIcon,
    CheerIcon,
    Chevron2LeftIcon,
    Chevron2RightIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronLineLeftIcon,
    ChevronLineRightIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleDotIcon,
    CircleIcon,
    ClockFillIcon,
    ClockIcon,
    CloudArrowDownFillIcon,
    CloudArrowDownIcon,
    CloudArrowUpFillIcon,
    CloudArrowUpIcon,
    CloudFillIcon,
    CloudIcon,
    CloudTickFillIcon,
    CloudTickIcon,
    CopyFillIcon,
    CopyIcon,
    CrossCircleFillIcon,
    CrossCircleIcon,
    CrossIcon,
    DocFillIcon,
    DocIcon,
    DocPencilFillIcon,
    DocPencilIcon,
    DollarIcon,
    DownloadIcon,
    DragHandleIcon,
    EllipsisHorizontalIcon,
    EllipsisVerticalIcon,
    EnvelopeFillIcon,
    EnvelopeIcon,
    EnvelopeOpenFillIcon,
    EnvelopeOpenIcon,
    EraserIcon,
    ExclamationCircleFillIcon,
    ExclamationCircleIcon,
    ExclamationTriangleFillIcon,
    ExclamationTriangleIcon,
    ExternalIcon,
    EyeFillIcon,
    EyeIcon,
    EyeSlashFillIcon,
    EyeSlashIcon,
    FilterIcon,
    FloorPlanFillIcon,
    FloorPlanIcon,
    FullscreenCloseIcon,
    FullscreenOpenIcon,
    GearFillIcon,
    GearIcon,
    GlobeIcon,
    HeartFillIcon,
    HeartIcon,
    HomeOfficeFillIcon,
    HomeOfficeIcon,
    HouseFillIcon,
    HouseIcon,
    ICircleFillIcon,
    ICircleIcon,
    IdCardFillIcon,
    IdCardIcon,
    InboxFillIcon,
    InboxIcon,
    LanguageIcon,
    LightbulbFillIcon,
    LightbulbIcon,
    LinkIcon,
    ListIcon,
    LockFillIcon,
    LockIcon,
    LockOpenFillIcon,
    LockOpenIcon,
    LoginIcon,
    LogoutIcon,
    MagnifierIcon,
    MagnifierMinusIcon,
    MagnifierPlusIcon,
    MapFillIcon,
    MapIcon,
    MenuIcon,
    MergeIcon,
    MinusCircleFillIcon,
    MinusCircleIcon,
    MinusIcon,
    MinusSquareFillIcon,
    MinusSquareIcon,
    MultiChevronDownUpIcon,
    MultiChevronUpDownIcon,
    NavigationFillIcon,
    NavigationIcon,
    NonRecurringIcon,
    PencilFillIcon,
    PencilIcon,
    PencilStrokeFillIcon,
    PencilStrokeIcon,
    Person2FillIcon,
    Person2Icon,
    Person2MinusFillIcon,
    Person2MinusIcon,
    Person2PlusFillIcon,
    Person2PlusIcon,
    PersonFillIcon,
    PersonGearFillIcon,
    PersonGearIcon,
    PersonGroupFillIcon,
    PersonGroupIcon,
    PersonIcon,
    PersonMinusFillIcon,
    PersonMinusIcon,
    PersonOffFillIcon,
    PersonOffIcon,
    PersonPlusFillIcon,
    PersonPlusIcon,
    PhoneFillIcon,
    PhoneIcon,
    PinFillIcon,
    PinIcon,
    PlaceholderIcon,
    PlaceholderImageIcon,
    PlusCircleFillIcon,
    PlusCircleIcon,
    PlusIcon,
    PointIcon,
    PrinterFillIcon,
    PrinterIcon,
    QrIcon,
    QuestionmarkCircleFillIcon,
    QuestionmarkCircleIcon,
    ReadMoreIcon,
    RecurringIcon,
    RefreshIcon,
    ReplayIcon,
    RetryIcon,
    ReturnIcon,
    ShareIcon,
    SortAscendingIcon,
    SortDescendingIcon,
    SpeakerFillIcon,
    SpeakerIcon,
    Square2x2FillIcon,
    Square2x2Icon,
    SquareFillIcon,
    SquareIcon,
    SquareTickFillIcon,
    SquareTickIcon,
    StarFillIcon,
    StarHalfIcon,
    StarIcon,
    TabletFillIcon,
    TabletIcon,
    TextFillIcon,
    TextIcon,
    ThumbDownFillIcon,
    ThumbDownIcon,
    ThumbUpFillIcon,
    ThumbUpIcon,
    TickCircleFillIcon,
    TickCircleIcon,
    TickIcon,
    TicketFillIcon,
    TicketIcon,
    ToggleOffFillIcon,
    ToggleOffIcon,
    ToggleOnFillIcon,
    ToggleOnIcon,
    TriangleForwardFillIcon,
    TriangleForwardIcon,
    UploadIcon,
} from "../../src";

export const ICONS: JSX.Element[] = [
    // Album
    <AlbumIcon key="AlbumIcon" />,
    <AlbumFillIcon key="AlbumFillIcon" />,
    // Align
    <AlignLeftIcon key="AlignLeftIcon" />,
    <AlignCenterIcon key="AlignCenterIcon" />,
    <AlignRightIcon key="AlignRightIcon" />,
    <AlignJustifyIcon key="AlignJustifyIcon" />,
    // Arrow
    <ArrowDownIcon key="ArrowDownIcon" />,
    <ArrowLeftDownIcon key="ArrowLeftDownIcon" />,
    <ArrowLeftUpIcon key="ArrowLeftUpIcon" />,
    <ArrowLeftIcon key="ArrowLeftIcon" />,
    <ArrowRightDownIcon key="ArrowRightDownIcon" />,
    <ArrowRightUpIcon key="ArrowRightUpIcon" />,
    <ArrowRightIcon key="ArrowRightIcon" />,
    <ArrowUpIcon key="ArrowUpIcon" />,
    // Arrow Circle
    <ArrowDownCircleIcon key="ArrowDownCircleIcon" />,
    <ArrowLeftCircleIcon key="ArrowLeftCircleIcon" />,
    <ArrowRightCircleIcon key="ArrowRightCircleIcon" />,
    <ArrowUpCircleIcon key="ArrowUpCircleIcon" />,
    <ArrowDownCircleFillIcon key="ArrowDownCircleFillIcon" />,
    <ArrowLeftCircleFillIcon key="ArrowLeftCircleFillIcon" />,
    <ArrowRightCircleFillIcon key="ArrowRightCircleFillIcon" />,
    <ArrowUpCircleFillIcon key="ArrowUpCircleFillIcon" />,
    // Bell
    <BellIcon key="BellIcon" />,
    <BellFillIcon key="BellFillIcon" />,
    // Bin
    <BinIcon key="BinIcon" />,
    <BinFillIcon key="BinFillIcon" />,
    // Bookmark
    <BookmarkIcon key="BookmarkIcon" />,
    <BookmarkFillIcon key="BookmarkFillIcon" />,
    // Box
    <BoxIcon key="BoxIcon" />,
    <BoxFillIcon key="BoxFillIcon" />,
    // Briefcase
    <BriefcaseIcon key="BriefcaseIcon" />,
    <BriefcaseFillIcon key="BriefcaseFillIcon" />,
    // Building
    <BuildingIcon key="BuildingIcon" />,
    // Calendar
    <CalendarIcon key="CalendarIcon" />,
    <CalendarFillIcon key="CalendarFillIcon" />,
    <CalendarEventIcon key="CalendarEventIcon" />,
    <CalendarEventFillIcon key="CalendarEventFillIcon" />,
    <CalendarPlusIcon key="CalendarPlusIcon" />,
    <CalendarPlusFillIcon key="CalendarPlusFillIcon" />,
    <CalendarTickIcon key="CalendarTickIcon" />,
    <CalendarTickFillIcon key="CalendarTickFillIcon" />,
    <CalendarCrossIcon key="CalendarCrossIcon" />,
    <CalendarCrossFillIcon key="CalendarCrossFillIcon" />,
    <CalendarDotIcon key="CalendarDotIcon" />,
    <CalendarDotFillIcon key="CalendarDotFillIcon" />,
    <CalendarPencilIcon key="CalendarPencilIcon" />,
    <CalendarPencilFillIcon key="CalendarPencilFillIcon" />,
    // Camera
    <CameraIcon key="CameraIcon" />,
    <CameraFillIcon key="CameraFillIcon" />,
    // Car
    <CarIcon key="CarIcon" />,
    // Caret
    <CaretLeftIcon key="CaretLeftIcon" />,
    <CaretRightIcon key="CaretRightIcon" />,
    <CaretUpIcon key="CaretUpIcon" />,
    <CaretDownIcon key="CaretDownIcon" />,
    // Chart
    <ChartIcon key="ChartIcon" />,
    <ChartFillIcon key="ChartFillIcon" />,
    // Cheer
    <CheerIcon key="CheerIcon" />,
    <CheerFillIcon key="CheerFillIcon" />,
    // Chevron
    <ChevronDownIcon key="ChevronDownIcon" />,
    <ChevronLeftIcon key="ChevronLeftIcon" />,
    <ChevronRightIcon key="ChevronRightIcon" />,
    <ChevronUpIcon key="ChevronUpIcon" />,
    <ChevronLineLeftIcon key="ChevronLineLeftIcon" />,
    <ChevronLineRightIcon key="ChevronLineRightIcon" />,
    <Chevron2LeftIcon key="Chevron2LeftIcon" />,
    <Chevron2RightIcon key="Chevron2RightIcon" />,
    // Circle
    <CircleIcon key="CircleIcon" />,
    <CircleDotIcon key="CircleDotIcon" />,
    // Clock
    <ClockIcon key="ClockIcon" />,
    <ClockFillIcon key="ClockFillIcon" />,
    // Cloud
    <CloudIcon key="CloudIcon" />,
    <CloudFillIcon key="CloudFillIcon" />,
    <CloudArrowUpIcon key="CloudArrowUpIcon" />,
    <CloudArrowUpFillIcon key="CloudArrowUpFillIcon" />,
    <CloudArrowDownIcon key="CloudArrowDownIcon" />,
    <CloudArrowDownFillIcon key="CloudArrowDownFillIcon" />,
    <CloudTickIcon key="CloudTickIcon" />,
    <CloudTickFillIcon key="CloudTickFillIcon" />,
    // Copy
    <CopyIcon key="CopyIcon" />,
    <CopyFillIcon key="CopyFillIcon" />,
    // Cross
    <CrossIcon key="CrossIcon" />,
    <CrossCircleIcon key="CrossCircleIcon" />,
    <CrossCircleFillIcon key="CrossCircleFillIcon" />,
    // Download
    <DownloadIcon key="DownloadIcon" />,
    // Doc
    <DocIcon key="DocIcon" />,
    <DocFillIcon key="DocFillIcon" />,
    <DocPencilIcon key="DocPencilIcon" />,
    <DocPencilFillIcon key="DocPencilFillIcon" />,
    // Dollar
    <DollarIcon key="DollarIcon" />,
    // DragHandle
    <DragHandleIcon key="DragHandleIcon" />,
    // Ellipsis
    <EllipsisHorizontalIcon key="EllipsisHorizontalIcon" />,
    <EllipsisVerticalIcon key="EllipsisVerticalIcon" />,
    // Evelope
    <EnvelopeIcon key="EnvelopeIcon" />,
    <EnvelopeFillIcon key="EnvelopeFillIcon" />,
    <EnvelopeOpenIcon key="EnvelopeOpenIcon" />,
    <EnvelopeOpenFillIcon key="EnvelopeOpenFillIcon" />,
    // Eraser
    <EraserIcon key="EraserIcon" />,
    // Exclamation
    <ExclamationCircleIcon key="ExclamationCircleIcon" />,
    <ExclamationCircleFillIcon key="ExclamationCircleFillIcon" />,
    <ExclamationTriangleIcon key="ExclamationTriangleIcon" />,
    <ExclamationTriangleFillIcon key="ExclamationTriangleFillIcon" />,
    // External
    <ExternalIcon key="ExternalIcon" />,
    // Eye
    <EyeIcon key="EyeIcon" />,
    <EyeFillIcon key="EyeFillIcon" />,
    <EyeSlashIcon key="EyeSlashIcon" />,
    <EyeSlashFillIcon key="EyeSlashFillIcon" />,
    // Filter
    <FilterIcon key="FilterIcon" />,
    // FloorPlan
    <FloorPlanIcon key="FloorPlanIcon" />,
    <FloorPlanFillIcon key="FloorPlanFillIcon" />,
    // Full Screen
    <FullscreenOpenIcon key="FullscreenOpenIcon" />,
    <FullscreenCloseIcon key="FullscreenCloseIcon" />,
    // Gear
    <GearIcon key="GearIcon" />,
    <GearFillIcon key="GearFillIcon" />,
    // Globe
    <GlobeIcon key="GlobeIcon" />,
    // Heart
    <HeartFillIcon key="HeartFillIcon" />,
    <HeartIcon key="HeartIcon" />,
    // HomeOffice
    <HomeOfficeIcon key="HomeOffice" />,
    <HomeOfficeFillIcon key="HomeOfficeFill" />,
    // House
    <HouseIcon key="HouseIcon" />,
    <HouseFillIcon key="HouseFillIcon" />,
    // I-Circle
    <ICircleIcon key="ICircleIcon" />,
    <ICircleFillIcon key="ICircleFillIcon" />,
    // Id Card
    <IdCardIcon key="IdCardIcon" />,
    <IdCardFillIcon key="IdCardFillIcon" />,
    // Inbox
    <InboxIcon key="InboxIcon" />,
    <InboxFillIcon key="InboxFillIcon" />,
    // Language
    <LanguageIcon key="LanguageIcon" />,
    // Lightbulb
    <LightbulbIcon key="LightbulbIcon" />,
    <LightbulbFillIcon key="LightbulbFillIcon" />,
    // List
    <ListIcon key="ListIcon" />,
    // Lock
    <LockIcon key="LockIcon" />,
    <LockFillIcon key="LockFillIcon" />,
    <LockOpenIcon key="LockOpenIcon" />,
    <LockOpenFillIcon key="LockOpenFillIcon" />,
    // Link
    <LinkIcon key="LinkIcon" />,
    // Login
    <LoginIcon key="LoginIcon" />,
    // Logout
    <LogoutIcon key="LogoutIcon" />,
    // Magnifier
    <MagnifierIcon key="MagnifierIcon" />,
    <MagnifierPlusIcon key="MagnifierPlusIcon" />,
    <MagnifierMinusIcon key="MagnifierMinusIcon" />,
    // Map
    <MapIcon key="MapIcon" />,
    <MapFillIcon key="MapFillIcon" />,
    // Menu
    <MenuIcon key="MenuIcon" />,
    // Merge
    <MergeIcon key="MergeIcon" />,
    // Minus
    <MinusIcon key="MinusIcon" />,
    <MinusCircleIcon key="MinusCircleIcon" />,
    <MinusCircleFillIcon key="MinusCircleFillIcon" />,
    <MinusSquareIcon key="MinusSquareIcon" />,
    <MinusSquareFillIcon key="MinusSquareFillIcon" />,
    // Multi Chevron
    <MultiChevronDownUpIcon key="MultiChevronDownUpIcon" />,
    <MultiChevronUpDownIcon key="MultiChevronUpDownIcon" />,
    // Navigation
    <NavigationIcon key="NavigationIcon" />,
    <NavigationFillIcon key="NavigationFillIcon" />,
    // NonRecurring
    <NonRecurringIcon key="NonRecurringIcon" />,
    // Pencil
    <PencilIcon key="PencilIcon" />,
    <PencilFillIcon key="PencilFillIcon" />,
    <PencilStrokeIcon key="PencilStrokeIcon" />,
    <PencilStrokeFillIcon key="PencilStrokeFillIcon" />,
    // Person
    <PersonIcon key="PersonIcon" />,
    <PersonFillIcon key="PersonFillIcon" />,
    <PersonPlusIcon key="PersonPlusIcon" />,
    <PersonPlusFillIcon key="PersonPlusFillIcon" />,
    <PersonMinusIcon key="PersonMinusIcon" />,
    <PersonMinusFillIcon key="PersonMinusFillIcon" />,
    <PersonOffIcon key="PersonOffIcon" />,
    <PersonOffFillIcon key="PersonOffFillIcon" />,
    <PersonGearIcon key="PersonGearIcon" />,
    <PersonGearFillIcon key="PersonGearFillIcon" />,
    <PersonGroupIcon key="PersonGroupIcon" />,
    <PersonGroupFillIcon key="PersonGroupFillIcon" />,
    <Person2Icon key="Person2Icon" />,
    <Person2FillIcon key="Person2FillIcon" />,
    <Person2PlusIcon key="Person2PlusIcon" />,
    <Person2PlusFillIcon key="Person2PlusFillIcon" />,
    <Person2MinusIcon key="Person2MinusIcon" />,
    <Person2MinusFillIcon key="Person2MinusFillIcon" />,
    // Phone
    <PhoneIcon key="PhoneIcon" />,
    <PhoneFillIcon key="PhoneFillIcon" />,
    // Pin
    <PinIcon key="PinIcon" />,
    <PinFillIcon key="PinFillIcon" />,
    // Placeholder
    <PlaceholderImageIcon key="PlaceholderImageIcon" />,
    <PlaceholderIcon key="PlaceholderIcon" />,
    // Plus
    <PlusIcon key="PlusIcon" />,
    <PlusCircleIcon key="PlusCircleIcon" />,
    <PlusCircleFillIcon key="PlusCircleFillIcon" />,
    // Point
    <PointIcon key="PointIcon" />,
    // Printer
    <PrinterIcon key="PrinterIcon" />,
    <PrinterFillIcon key="PrinterFillIcon" />,
    // Qr
    <QrIcon key="QrIcon" />,
    // QuestionMark
    <QuestionmarkCircleIcon key="QuestionmarkCircleIcon" />,
    <QuestionmarkCircleFillIcon key="QuestionmarkCircleFillIcon" />,
    // Read More
    <ReadMoreIcon key="ReadMoreIcon" />,
    // Recurring
    <RecurringIcon key="RecurringIcon" />,
    // Refresh
    <RefreshIcon key="RefreshIcon" />,
    // Replay
    <ReplayIcon key="ReplayIcon" />,
    // Retry
    <RetryIcon key="RetryIcon" />,
    // Return
    <ReturnIcon key="ReturnIcon" />,
    // Share
    <ShareIcon key="ShareIcon" />,
    // Sort
    <SortDescendingIcon key="SortDescendingIcon" />,
    <SortAscendingIcon key="SortAscendingIcon" />,
    // Star
    <StarIcon key="StarIcon" />,
    <StarHalfIcon key="StarHalfIcon" />,
    <StarFillIcon key="StarFillIcon" />,
    // Speaker
    <SpeakerIcon key="SpeakerIcon" />,
    <SpeakerFillIcon key="SpeakerFillIcon" />,
    // Square
    <SquareIcon key="SquareIcon" />,
    <SquareFillIcon key="SquareFillIcon" />,
    <SquareTickIcon key="SquareTickIcon" />,
    <SquareTickFillIcon key="SquareTickFillIcon" />,
    <Square2x2Icon key="Square2x2Icon" />,
    <Square2x2FillIcon key="Square2x2FillIcon" />,
    //Tablet
    <TabletIcon key="TabletIcon" />,
    <TabletFillIcon key="TabletFillIcon" />,
    // Text
    <TextIcon key="TextIcon" />,
    <TextFillIcon key="TextFillIcon" />,
    // ThumbUp
    <ThumbDownIcon key="ThumbDownIcon" />,
    <ThumbDownFillIcon key="ThumbDownFillIcon" />,
    <ThumbUpIcon key="ThumbUpIcon" />,
    <ThumbUpFillIcon key="ThumbUpFillIcon" />,
    // Tick
    <TickIcon key="TickIcon" />,
    <TickCircleIcon key="TickCircleIcon" />,
    <TickCircleFillIcon key="TickCircleFillIcon" />,
    // Ticket
    <TicketIcon key="TicketIcon" />,
    <TicketFillIcon key="TicketFillIcon" />,
    // Toggle
    <ToggleOffIcon key="ToggleOffIcon" />,
    <ToggleOffFillIcon key="ToggleOffFillIcon" />,
    <ToggleOnIcon key="ToggleOnIcon" />,
    <ToggleOnFillIcon key="ToggleOnFillIcon" />,
    // Triangle
    <TriangleForwardIcon key="TriangleForwardIcon" />,
    <TriangleForwardFillIcon key="TriangleForwardFillIcon" />,
    // Upload
    <UploadIcon key="UploadIcon" />,
];
